### ISSUE TITLE
Intro Slides for Final Presentation

### ISSUE THREAD

**Issue by tmyarow** [tmyarow/CS3704_Project#1]
Add slide(s) that give a brief introduction to the project containing motivation, background, etc.

**Comment by aaryashahk** [comment]
Introduction & Motivation

Introduction
Restaurants are fast-paced environments, lots of moving parts simultaneously.
Comes with a lot of overhead as there is the payroll for employees to take care of, orders to manage, inventory to keep track of, and scheduling of employees.
Optimization of each process would keep things more succinct.

Motivation
Automating the entire system would be best as it would lead to a more centralized system that promotes ease of access.
A centralized system would compose of payroll, inventory management, food deliveries, and overall data collection.

**Comment by aaryashahk** [comment]
Closing the issue.
