### ISSUE TITLE
Name of app?

### ISSUE THREAD

**Issue by amrios** [tmyarow/CS3704_Project#6]
Just would like to comment that while I was doing the wireframes, I created a placeholder logo with a temp name called "restaurantApp". This logo was made for the purpose of demonstrating that some logo should be there. When I opened the presentation, I saw that this placeholder logo was on the title page.

![image](https://user-images.githubusercontent.com/3386201/165596563-1eefa286-60c9-46ab-b7bf-6b7825f2b702.png)

The name and logo is very generic and simple. Should we come up with a better name?

**Comment by Singha22** [comment]
The logo looks good to me. I say we should keep it.

**Comment by Vincent-Stevens** [comment]
I agree. Lets run with it
